### ISSUE TITLE
'stocker' is not a package

### ISSUE THREAD

**Issue by jseila** [jcamiloangarita/stocker#10]
I installed this tonight on macOS Catalina. I am on Python 3.7 and I keep getting this error when using the example code:
    from stocker.predict import tomorrow
ModuleNotFoundError: No module named 'stocker.predict'; 'stocker' is not a packag

However the module is installed using Python3.7 pip -m install stocker and I got the message Successfully installed stocker-0.1.5

**Comment by jcamiloangarita** [comment]
It depends on where are you executing the code from... e.g. using any IDE (like Pycharm), 'stocker' must be installed in the **virtual environment** you are using at the moment. Just check that the interpreter is actually including the package (:
