### ISSUE TITLE
compatiblity with latest python

### ISSUE THREAD

**Issue by malikasinger1** [jcamiloangarita/stocker#15]
https://www.tensorflow.org/install/pip#system-requirements

just wanted to make sure if your package is compatible with python3.9 and tensorflow 2.5
Actually I have a project to run includes this package and I am having lots of problem in compatibility

thanks in advance

**Comment by malikasinger1** [comment]
why dont you have mentioned dependency versions in your requirement.txt it is installing tensorflow 2.5 which is released few days ago and giving errors 

AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

and probably it is because wrong version of tensorflow, well my code is not working yet

**Comment by jcamiloangarita** [comment]
dependency versions were included and tests are running successfully with python 3.7, 3.8 and 3.9.

[![tests](https://github.com/jcamiloangarita/stocker/actions/workflows/tests.yml/badge.svg)](https://github.com/jcamiloangarita/stocker/actions/workflows/tests.yml)
