### ISSUE TITLE
Yahoo data reading error

### ISSUE THREAD

**Issue by evanstjabadi** [jcamiloangarita/stocker#19]
Hi @jcamiloangarita,

What a cool library this is.

I am running into data fetching issues with yahoo. I experienced this even before seeing this library.

![image](https://user-images.githubusercontent.com/31672668/124838828-ea55c280-df87-11eb-8752-fe8430ee19d2.png)

Is there a way to get around this?

I used yfinance tool to pull data from yahoo.

**Comment by verystrongbuy** [comment]
I’m getting the same error, I think it’s an issue with yfinance...seems to be down.

**Comment by evanstjabadi** [comment]
@verystrongbuy - seems like the below works:

- `pip install yfinance`

- Then in the stocker code, replace the data fetch method with:
- `+import yfinance as yf`
- `+df = yf.download(stock, start, end)`

instead of

- `-from pandas_datareader import data`
- `-df = data.DataReader(stock, 'yahoo', start, end)`


It seems like the yahoo finance URL end-point is broken or discontinued: [Stackoverflow](https://stackoverflow.com/questions/44030983/yahoo-finance-url-not-working)

**Comment by verystrongbuy** [comment]
You are the man. Thank you!

**Comment by jcamiloangarita** [comment]
Hi, thank you guys for being part of this project. Had not time to reply before, sorry for that.

As you mentioned, there was an issue with fetching data by using pandas-datareader. As @evanstjabadi suggested, yfinance is now the way to do it, so the fix was added and new version of stocker released (v0.1.10).

**Comment by verystrongbuy** [comment]
Thank you very much! Works great now. Appreciate all of your hard work. Fantastic resource.
