### ISSUE TITLE
methods to validate the accuracy?

### ISSUE THREAD

**Issue by aspiringguru** [jcamiloangarita/stocker#4]
just found this, running comparitive tests against other methods. still to check if I'm using this package optimally.

Any suggestions on areas of the code to look at to understand the accuracy and tuning better?

[mostly, thanks for publishing, was not expecting to find someting as complete as this. currently refreshing myself on tensorflow after an abscence.]

**Comment by jcamiloangarita** [comment]
Hi @aspiringguru, there are different parameters in the  [tomorrow](https://github.com/jcamiloangarita/stocker/blob/da15b82487c6a2eaac46c030ca3dcbeb235c1a09/stocker/predict.py#L6) predictive function that you could play with. Also, you can experiment by modifying the [layers](https://github.com/jcamiloangarita/stocker/blob/da15b82487c6a2eaac46c030ca3dcbeb235c1a09/stocker/lstm.py#L54) applied for the model. For a general overview of the package main function please check the [tutorial](https://github.com/jcamiloangarita/stocker/blob/master/tutorial/Stocker%20-%20Analysis.ipynb).

Feel free to experiment with the code, any idea will be very welcome.

Thank you and regards.
