### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by rakisg** [jcamiloangarita/stocker#6]
Im getting an import error when I used the following code
from stocker import Stocker

Error:
ImportError: cannot import name 'Stocker' from 'stocker'    C:\software\python\Anaconda3\lib\site-packages\stocker\__init__.py

I'm using Anaconda 3.7 and was able to install Stocker successfully

**Comment by jcamiloangarita** [comment]
Hi rakisg,

Just import the package itself if it's already installed within your environment:
~~from stocker import Stocker~~  import stocker

Check this example:
![image](https://user-images.githubusercontent.com/52009346/82753678-b5100480-9dc7-11ea-9c1a-b0385337cede.png)

**Comment by rakisg** [comment]
Thanks jcamiloangarita !
I got confused with Stocker :)
https://github.com/WillKoehrsen/Data-Analysis/tree/master/stocker
Looks like your package is working as expected thanks..
