### ISSUE TITLE
Repeated feature in get_lstm_input() function?

### ISSUE THREAD

**Issue by HTian1997** [jcamiloangarita/stocker#8]
https://github.com/jcamiloangarita/stocker/blob/da15b82487c6a2eaac46c030ca3dcbeb235c1a09/stocker/lstm.py#L23-L24

Here, it is just repeated `j` times of the same feature. Shouldn't be `features.append(data[i - steps + j, :]) ` instead?

**Comment by jcamiloangarita** [comment]
You are completely right! It will be corrected asap. Thanks for the observation 🥇
